version: "2"
services:
  node:
    image: "node:lts-alpine"
    platform: linux/amd64
    user: "node"
    working_dir: /home/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/app
    expose:
      - "3010"
    ports:
      - "3010:3010"
    command: "npm start"