version: 2.1

executors:
  node_lts:
    docker:
      - image: cimg/node:lts
    working_directory: ~/app

jobs:
  build_and_push:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - run:
        name: Install pnpm
        command: |
          npm install -g pnpm

      - run:
        name: Clone front-end source code
        command: |
          git clone https://github.com/HAIZAKURA/mytools-vue.git
          cd mytools-vue

      - run:
        name: Build front-end
        command: |
          pnpm install
          pnpm build

      - run:
        name: Move front-end build files
        command: |
          mv dist ../public

      - run:
        name: Delete front-end source code
        command: |
          cd ..
          rm -rf mytools-vue

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            TAG=3.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/mytools-vue:$TAG .

      - run:
          name: Push Docker image
          command: |
            TAG=3.0.$CIRCLE_BUILD_NUM
            docker push $DOCKERHUB_USERNAME/mytools-vue:$TAG

workflows:
  build_and_deploy:
    jobs:
      - build_and_push
