version: 2.1

executors:
  node_lts:
    docker:
      - image: cimg/node:lts
    working_directory: ~/app

jobs:
  build_and_push:
    executor: node_lts
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            npm install --global corepack@latest
            corepack enable
            corepack prepare pnpm@latest-10 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Clone front-end source code
          command: |
            git clone https://github.com/HAIZAKURA/mytools-vue.git
            cd mytools-vue
      - run:
          name: Install Dependencies and Build
          command: |
            pnpm install
            pnpm build
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
      - run:
          name: Move front-end build files
          command: |
            mv mytools-vue/dist ./public
      - run:
          name: Delete front-end source code
          command: rm -rf mytools-vue
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            TAG=3.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/mytools-vue:$TAG .
      - run:
          name: Push Docker image
          command: |
            TAG=3.0.$CIRCLE_BUILD_NUM
            docker push $DOCKERHUB_USERNAME/mytools-vue:$TAG

workflows:
  build_and_deploy:
    jobs:
      - build_and_push