name: Build Docker image & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    -
      name: Enable pnpm
      run: corepack enable pnpm
    -
      name: Clone front-end source code and build
      run: git clone https://github.com/HAIZAKURA/mytools-vue.git || cd ./mytools-vue || pnpm i || pnpm run build
    -
      name: Move build output
      run: mv ./dist ../public
    -
      name: Delete front-end source code
      run: cd .. || rm -rf ./mytools-vue
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build Docker image and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: hhbilly/mytools:$(date +%s)
